baseURL = 'https://b3x.dev/'
languageCode = 'en-us'
title = "b3x.dev"
theme = "triple-hyde"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Algorithm, Go, Cloud, Open Source"
layoutReverse = false

[params.utterances]
repo = "JulienBreux/b3x.dev"

since = 2024
copyright = 'Julien Breux'
license = 'CC BY-SA 4.0'
licenseURL = 'https://creativecommons.org/licenses/by-sa/4.0/'

[params.social]
github = "JulienBreux"
gitlab = "JulienBreux"
bitbucket = "JulienBreux"
twitter = "JulienBreux"
linkedin = "JulienBreux"
keybase = "JulienBreux"
medium = "JulienBreux"
gravatar = "julien.breux@gmail.com"

[[menu.main]]
name = "About"
identifier = "about"
url = "/about/"

[module]
[[module.imports]]
path = "github.com/hugomods/utterances"
